modLoader="javafml"
loaderVersion="[34,)"
license="MIT"
[[mods]]
modId="bread_block_mod"
version="${mod_version}"
displayName="Bread Block Mod"
updateJSONURL=""
#displayTest="" #optional
credits="Thanks to the developers!"
authors="Your Name"
description="A mod that adds a bread block to Minecraft."

[[dependencies.bread_block_mod]]
modId="forge"
mandatory=true
versionRange="[34,)"
ordering="NONE"
side="BOTH"